### ISSUE TITLE
#include files that implement helper functions are not seen by kernel source being compiled

### ISSUE THREAD

**Issue by cudaGuy** [jrprice/Oclgrind#119]
# include "helper.h"

__kernel test(__global *A, __global *B)
{
   int x = get_global_id(0);
  B[x] = helperFunc(A[x]); //helperFunc is defined in header "helper.h"
}

This kernel fails to compile with an error "Undefined external function: helperFunc

// helper.h
inline float helperFunc(float x)
{
   return x *x;
}

**Comment by jrprice** [comment]
I'm unable to reproduce this issue on my own system. Can you provide a more complete test case that exhibits this issue?

Are you using the `inline` keyword when declaring `helperFunc` by any chance?

**Comment by cudaGuy** [comment]
Yes. That is correct. Code snipped is updated. Do you think this can be fixed?

**Comment by jrprice** [comment]
OK, this is a known issue with the way that `inline` is being used, which is technically invalid for C99 or OpenCL C programs. See more on the ["inline functions" section of the troubleshooting page](https://github.com/jrprice/Oclgrind/wiki/Troubleshooting).

The simple fix is to use `static inline` instead of just `inline`, which should also work for all other OpenCL platforms.

**Comment by cudaGuy** [comment]
Understood. Thank you
