### ISSUE TITLE
Oclgrind crash

### ISSUE THREAD

**Issue by mpflanzer** [jrprice/Oclgrind#121]
The attached kernel makes Oclgrind crash with the following error:
```
oclgrind-kernel: /work/clreduce/install/include/llvm/IR/Instructions.h:866: static llvm::GetElementPtrInst* llvm::GetElementPtrInst::Create(llvm::Type*, llvm::Value*, llvm::ArrayRef<llvm::Value*>, const llvm::Twine&, llvm::Instruction*): Assertion `PointeeType == cast<PointerType>(Ptr->getType()->getScalarType())->getElementType()' failed.
Aborted (core dumped)
```

The problem is in `src/core/common.cpp` line 454. `expr->getType()` returns `*i8` but the expected type for the operand is `i8`. It can be fixed by passing `nullptr` instead of `expr->getType()` to let LLVM deduced the type automatically from the operand. I'm not sure though if this is the best solution.

I compiled and linked Oclgrind against LLVM 3.9.1. I have not seen this issue before so I suspect something between 3.8 and 3.9 changed.

[crash.cl.txt](https://github.com/jrprice/Oclgrind/files/492959/crash.cl.txt)
[crash.sim.txt](https://github.com/jrprice/Oclgrind/files/492960/crash.sim.txt)

**Comment by jrprice** [comment]
Thanks for catching this. Using `expr->getType()` was definitely wrong, the pointee type should have been derived from `operands[0]` (the base pointer) instead. Since the LLVM function in question will infer the correct type automatically if we just pass `nullptr` as you point out, this is a better fix anyway.

Also added a regression test for this.
