### ISSUE TITLE
Make constant buffer size configurable

### ISSUE THREAD

**Issue by JonnoFTW** [jrprice/Oclgrind#129]
Most devices (that I've seen) have 64kB of constant memory but Oclgrind uses 1024kB. This creates problems when you test on oclgrind and it works and then on a real device and it fails due to constant buffer usage.

The buffer size is defined here: https://github.com/jrprice/Oclgrind/blob/c66119df95ea78a89236b9f54c6e1dd8d420f786/src/runtime/runtime.cpp#L30

It would be useful if this value could be configured at run time (or compile time at least). Additionally, ideally we should be able to configure any of the device options to replicate the specs of any device.

**Comment by jrprice** [comment]
I agree that we should make this limit (and others like global memory, local memory etc) configurable at runtime.

At the moment, all of these limits are entirely arbitrary, and Oclgrind won't actually complain if you exceed them. It would be easy to add a flag/environment variable to change the value that Oclgrind reports for these queries, but it would be a little more work to make it so that Oclgrind actually reports an error if you try to exceed the limits.

**Comment by JonnoFTW** [comment]
Having a strict memory limit runtime option would be best, especially when you're trying to debug kernels that might exceed memory limits. If I was more familiar with the code base (and c++) I'd help out.

**Comment by jrprice** [comment]
As of 695897f and 2fc90f8, there is a `--constant-mem-size` flag that allows the size of constant memory to be configured at runtime. The amount of constant memory used by a kernel is now checked against this limit at enqueue. I've also changed the default to 64 kilobytes. There will be a new release with these features very soon.
