### ISSUE TITLE
PyOpencl and Oclgrind ignores quotes in include strings

### ISSUE THREAD

**Issue by SimLeek** [jrprice/Oclgrind#131]
Here's the error I got:

 `Build on <pyopencl.Device 'Oclgrind Simulator' on 'Oclgrind' at 0x985c40>:`
 
 `error: error reading 'files\anaconda3\envs\py27\lib\site-packages\pyopencl\cl"'`
 
 `(options: -I "c:\program files\anaconda3\envs\py27\lib\site-packages\pyopencl\cl")`
 `(source saved as c:\users\joshm\appdata\local\temp\tmp0lksse.cl)`

That didn't happen on either of the other of my opencl devices, which likely also need those cl files, my command prompt correctly passes whole quoted strings, and that was a cl error, so it's likely a problem with the most recent windows build of Oclgrind.

This is similar to https://github.com/jrprice/Oclgrind/pull/68, but this is the include file rather than the binary.

**Comment by jrprice** [comment]
Reproduced on macOS. Looks like Oclgrind will need to manually handle quotes and escape characters to deal with these sorts of arguments, which is a pain, but doable.

**Comment by jrprice** [comment]
If you wanted to test this without waiting for the next official release (which might be a while), I've uploaded Windows binaries from my nightly build here:

https://www.dropbox.com/s/1a3igee982lrr4v/Oclgrind-16.10-Windows-9fe6c0ee.zip?dl=0

(note that these haven't been tested thoroughly and a bunch of other things have changed since the last release).
