### ISSUE TITLE
Assertion 'Uncorrected typos!' for undeclared identifiers

### ISSUE THREAD

**Issue by ChrisCummins** [jrprice/Oclgrind#140]
Hi James,

For *some* kernels which contain undeclared identifiers, I get a clang assertion:

```
.../Sema.cpp:289: clang::Sema::~Sema(): Assertion `DelayedTypos.empty() && "Uncorrected typos!"' failed
```

Here's an example:

```c
kernel void A(global float* a) {
  a[0] = max(a[undeclared], 0);
}
```

This is using Oclgrind 16.10 built with LLVM 3.9. I am unable to reproduce the problem when compiling only clang (same 3.9 version):

```
$ clang -cc1 -x cl -include $opencl_header foo.cl
... error: use of undeclared identifier 'undeclared'
```

Cheers,
Chris

**Comment by jrprice** [comment]
Hmm, I'm afraid I *do* see this assertion when just compiling with Clang 3.9 on the command-line. Can you confirm that you're definitely invoking the right Clang (3.9 debug build)?

FWIW, frontend Clang crashes are very rarely Oclgrind's fault (though I won't say never), since it just invokes Clang directly in pretty much the same way that we do on the command-line (with maybe one or two extra flags). Crashes inside LLVM passes and components on the other hand potentially could be the result of some small transformations that Oclgrind performs.

**Comment by ChrisCummins** [comment]
ack, I'm sorry. Turns out I was using the wrong `opencl-c.h` header, and that was somehow preventing the assertion. Looks like it's fixed in clang trunk anyway
