### ISSUE TITLE
Can oclgrind support arm or aarch64 platform?

### ISSUE THREAD

**Issue by thiefuniverse** [jrprice/Oclgrind#163]
I want to check gpu memory leak in arm platform. Thanks :).

**Comment by jrprice** [comment]
I'm not sure I understand the question - Oclgrind doesn't simulate any specific architecture. You can tweak some parameters such as the number of compute units or sizes of memories to make it appear a bit more like a specific device in device queries, but otherwise the simulation is entirely architecture-agnostic. It also doesn't have any ability to check for memory leaks, only invalid memory accesses.

**Comment by thiefuniverse** [comment]
thanks :)
