### ISSUE TITLE
Oclgrind does not run with llvm 7

### ISSUE THREAD

**Issue by luspi** [jrprice/Oclgrind#164]
Hi,

I am running Arch Linux and I am unable to use Oclgrind on an up-to-date system with Oclgrind 18.3 compiled from source using cmake/make.

When running `oclgrind <executable>` I get the following error message

```
: CommandLine Error: Option 'print-summary-global-ids' registered more than once!
LLVM ERROR: inconsistency in registered CommandLine options 
```

I am, though, able to run `oclgrind --help`, I get the normal help message.

LLVM installation:
```
$ clang --version
clang version 7.0.1 (tags/RELEASE_701/final)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```

Any suggestion as to how to solve the issue? Let me know if I you need more info...

**Comment by jrprice** [comment]
Were you able to run `make test` successfully after you built Oclgrind?

This sort of error usually occurs because something else invoked by the application is trying to use LLVM at the same time (e.g. the application itself or a library it depends on uses LLVM in some way).

**Comment by luspi** [comment]
Just ran `make test` and all the tests without exception fail. Is there a way to get more information from the tests why they failed?

**Comment by jrprice** [comment]
You can usually get at least the failure message if you run `ctest . --output-on-failure`.

**Comment by luspi** [comment]
Hm, not sure that helps much, that's the error for all of them:
```
Running test with optimisations
Test returned non-zero value (1)
FAILED
```

**Comment by jrprice** [comment]
Yeah that's not great. I guess you could just run one of the tests directly from the build directory, e.g. `tests/apps/vecadd/vecadd`?

**Comment by luspi** [comment]
That might be why they fail:
```
$ tests/apps/vecadd/vecadd
Unable to find Oclgrind platform
```

**Comment by jrprice** [comment]
Ah my bad, when running the tests through CMake/make it actually does this:

    OCLGRIND_TESTING=1 ./oclgrind tests/apps/vecadd/vecadd

**Comment by luspi** [comment]
Ah, ok. That gives me the same error I get when trying to use oclgrind:
```
$ OCLGRIND_TESTING=1 ./oclgrind tests/apps/vecadd/vecadd
: CommandLine Error: Option 'print-summary-global-ids' registered more than once!
LLVM ERROR: inconsistency in registered CommandLine options
```

**Comment by jrprice** [comment]
OK, I've managed to reproduce this in an Arch Linux Docker image. I think the issue is arising from the fact that the Arch only provides dynamic libraries for Clang, and both static and dynamic for LLVM. Oclgrind is linking statically to LLVM and dynamically to Clang, and then weird things are happening.

You can fix this by editing the `target_link_libraries` call on line 231 of the root `CMakeLists.txt`, and changing `${LLVM_LIBS}` to just `LLVM`, which gets it to link against the dynamic libraries for LLVM as well.

I'll need to think about a better long term fix, since the above would presumably break things on systems that only have static Clang libraries instead of dynamic. I probably need to try and detect which versions are available and either use just static or just dynamic.

Just as I finished writing this, I remembered this is probably the same as issue #137, and indeed the last comment there even mentions Arch and points to this exact cause.

**Comment by luspi** [comment]
Perfect, thanks, that did the trick!

As there currently is only a git package for Arch Linux I created a non-git package for the latest version including a patch for llvm: https://aur.archlinux.org/packages/oclgrind

**Comment by jrprice** [comment]
> As there currently is only a git package for Arch Linux I created a non-git package for the latest version including a patch for llvm: https://aur.archlinux.org/packages/oclgrind

Awesome, thanks!
