### ISSUE TITLE
Add support to LLVM/Clang 11

### ISSUE THREAD

**Issue by huypn12** [jrprice/Oclgrind#193]
Hi,

I have tried to build OclGrind against LLVM/Clang11 toolchain and found a lot of build errors related to the change in API. I am trying to port OclGrind to LLVM 11 at 

[https://github.com/huypn12/Oclgrind](url)

at branch huypn12-clang11

Now the build is successful. Most of  the build errors related to
1. change of getVectorNumElements and getVectorElementType. I solved this by static cast llvm::Type in to llvm::VectorType in the cases that the later 2 methods are called.
2. change of llvm::ShuffleVectorInst::getMask(). I solved this by change getMask to getShuffleMaskForBitcode
3. remove -dwarf-column-info

I am not sure what I have done is correct. There are 3 tests still failed.

![grafik](https://user-images.githubusercontent.com/2792821/99262103-d9e8b000-281d-11eb-997f-0bce1885cc2c.png)

I would like to ask what was wrong with my adjustments to the code, why these tests failed, and how can I fix it?

Thank you.

**Comment by jrprice** [comment]
I pushed a commit that adds support for LLVM 11 earlier today: https://github.com/jrprice/Oclgrind/commit/5c781c52f4a3c713de847aa773e66d137b5398d3

I hit the same test failures as you, which were caused by the use of `getShuffleMaskForBitcode()`. Instead, I just used the constant mask values which you can get with `getMaskValue()`. Otherwise your changes sounds like they are the same as mine.

**Comment by huypn12** [comment]
Nice, I will try it. Thank you.

**Comment by huypn12** [comment]
In case you have time to answer :)
what is the difference between getShuffleMaskForBitcode() and getMaskValue()? Why did it cause the test failures, and why changing to getMaskValue solved the problem?

**Comment by jrprice** [comment]
> what is the difference between getShuffleMaskForBitcode() and getMaskValue()? Why did it cause the test failures, and why changing to getMaskValue solved the problem?

`getShuffleMaskForBitcode()` returns the LLVM IR representation of the mask (a `llvm::Constant` object), whereas `getMaskValue()` just returns the actual `int` value of the mask. The problem with `getShuffleMaskForBitcode()` was that the type of `llvm::Constant` being used wasn't handled by `WorkItem::getOperand()` (which maps an LLVM object to its actual value). This probably could have been fixed quite easily, but doing so was unnecessary since we can just get the mask value directly from the instruction instead with `getMaskValue()`.

Hope that helps!
