### ISSUE TITLE
Fatal errors with some external functions

### ISSUE THREAD

**Issue by Se6** [jrprice/Oclgrind#77]
With Oclgrind 15.5, getting some errors with some functions. It seems it does not like functions using kernel global parameters:

Reproducer with a trivial addVec type of kernel:
```
inline void addIt(global const float *a, global const float *b, global float *res)
{
    *res = *a + *b;
}

kernel void vecAdd(global const float *a,
						global const float *b,
						global float *result)
{
    int gid = get_global_id(0);
    // result[gid] = a[gid] + b[gid];
    addIt(a+gid, b+gid, result+gid);
}
```

Gives the following error:
```
OCLGRIND FATAL ERROR (/home/jprice/oclgrind-testing/cmake/src/oclgrind-15.5/src/core/WorkItem.cpp:1493)
Undefined external function: addIt
When creating kernel 'vecAdd'
Failed to create kernel
```

**Comment by jrprice** [comment]
This is actually due to misuse of the `inline` keyword. The fix is to declare your function as `static inline`, instead of just `inline`. We've had this issue for quite a few codes, but Oclgrind isn't the only OpenCL implementation that this causes a problem for.

There's a little more information under the **Inline Functions** section in our [Troubleshooting Wiki](https://github.com/jrprice/Oclgrind/wiki/Troubleshooting). Basically, `inline` in C99 is different to `inline` in C++ or GCC's C89 mode.

Let me know if this fixes things.

**Comment by Se6** [comment]
You're fast!
Yes indeed, that was the problem!
Thank a lot!

Seb
