### ISSUE TITLE
how to use more than one compute unit?

### ISSUE THREAD

**Issue by nogece** [jrprice/Oclgrind#85]
If I ran oclgrind, it always runs on only one compute unit. E.g.:

`>oclgrind clinfo
Number of platforms:                 1
  Platform Profile:              FULL_PROFILE
  Platform Version:              OpenCL 1.2 (Oclgrind 15.5)
  Platform Name:                 Oclgrind
  Platform Vendor:               University of Bristol
  Platform Extensions:               cl_khr_icd

  Platform Name:                 Oclgrind
Number of devices:               1
  Device Type:                   CL_DEVICE_TYPE_CPU
  Vendor ID:                     42h
  Max compute units:                 1
`
"--num-threads N" doesnt change that. Is there a way to simulate on several CUs?

**Comment by jrprice** [comment]
It would be fairly easy for me to add an command-line option/environment variable to allow the user to set the number of compute units to some arbitrary number. This won't affect the simulation though, since the number of compute units doesn't affect the execution of memory models in OpenCL.

Does your code use the number of compute units to change how it operates?

**Comment by jrprice** [comment]
As of 9782f85 there is now a `--compute-units` flag to change the number of compute units reported by the `clGetDeviceInfo(..., CL_DEVICE_MAX_COMPUTE_UNITS, ...)` query.
